sudo: required
services:
  - docker

before_install:
  - docker build -t hotcoconut/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true hotcoconut/react-test npm run test

after_success:
  - docker build -t hotcoconut/multi-client ./client
  - docker build -t hotcoconut/multi-nginx ./nginx
  - docker build -t hotcoconut/multi-server ./server
  - docker build -t hotcoconut/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push the to docker hub
  - docker push hotcoconut/multi-client 
  - docker push hotcoconut/multi-nginx
  - docker push hotcoconut/multi-server
  - docker push hotcoconut/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "multi-docker"
  env: "Multi-docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-143829176546"
  bucket_path: "multi-docker"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
  